repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args:
        - --check
        - --diff

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
        - --check
        - --diff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.940"
    hooks:
      - id: mypy
        additional_dependencies:
        - pydantic
        - types-python-dateutil

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      exclude: tests

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.265
    hooks:
    - id: ruff
