name: pratapocos CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.3-alpine
        env:
          POSTGRES_DB: db_test
          POSTGRES_PASSWORD: db_test_pwd_ci
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - run: poetry --version

      - name: Install dependencies
        run: |
          poetry install
          source `poetry env info --path`/bin/activate

      - name: Run Python Linter
        run: |
          ruff .

      - name: Run Formatter
        run: |
          black --check --diff .
          isort --check --diff .

      - name: Run Python Mypy
        run: |
          mypy .

      - name: Run Python Bandit
        run:
          bandit --exclude ./tests,./.venv,./dist --recursive .

      - name: Rodar migrations
        env:
          DATABASE_URL: postgres://postgres:db_test_pwd_ci@localhost:5432/db_test
        run: ./manage.py migrate --noinput

      - name: Tests
        env:
          DATABASE_URL: postgres://postgres:db_test_pwd_ci@localhost:5432/db_test
        run: pytest --cache-clear
